on: [workflow_dispatch]
name: Deploy Bicep
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ResourceGroupLocation: "northeurope"
    
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ secrets.AZURE_RG }} --location ${{ env.ResourceGroupLocation }}
          echo "Azure resource group created"

      # Deploy Bicep file
    - name: bicepDeploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./third-sample.bicep
        parameters: 'resourcesPrefix=${{ vars.RESOURCESPREFIX }}'
        failOnStdErr: false
        
    - run: echo ${{ steps.bicepDeploy.outputs.azureServiceBusNamespace }}

    - run: echo ${{ steps.bicepDeploy.outputs.functionAppName }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.47.0
        inlineScript: |
          $sbNamespaceId = (az servicebus namespace show --resource-group ${{ secrets.AZURE_RG }} --name  ${{ steps.bicepDeploy.outputs.azureServiceBusNamespace }} --query id --output tsv)
          $miFunctionAppPrincipalId = (az functionapp identity assign -g ${{ secrets.AZURE_RG }} -n ${{ steps.bicepDeploy.outputs.functionAppName }} --query principalId --output tsv)
          az role assignment create --assignee $miFunctionAppPrincipalId --role "Azure Service Bus Data Sender" --scope $sbNamespaceId
